codonTable = {}

f = open("codon_table")

raw = f.readlines()

list = []


for i in range(len(raw)):
    list.append(raw[i].split())

for i in range(len(list)):
    for j in range(len(list[i])):
        if j%2==0:
            codonTable[list[i][j]] = list[i][j + 1]

print(codonTable)

dict ={}

for key,value in codonTable.items():
    if not value in dict:
        dict[value]=1
    else:
        dict[value]+=1

print(dict)

cnt=1

s='MVQYSIWRFSNTCYTLDGDTPGETDIITSWDHVPFIPTQHWLGVFMEDQVTSCCSPGPCDMCMCTKNEPWDWPVVLEVRWTLVARCAWRFGSYINWCRFYQDFEEWLTALHPPEDCIIAAVACKDPRQGYCNQAVEPLEDPYELQFIGCMLHPMSGKFNLLTKMAEDCKEMNWIHPGKMNYVMVLMPEKHCMQFRRLNCFQPIPGVENYQEAHPMCQTMHDWVGAAMNRAFFRFTESRSQAWWGCIQGHMGQYNDVWMRLCYLPHIDPNKESFFKAGNYLSSGKVGYIVLKFMLTFIRYEAVNIESGTRHQTVGDSQESFHTCWGGRSMQEHVIRAFCAFNVLRNLPKMMNIEAWGIPVKNHKGTDEKYIYSYWLRADGCAWVMLFMCMFPTDPDLNHMKKPLLACEWVSPQPRSEPHKQANSDGYREQSCIWKPSQCRCQLHKYSTDAQIYHEAFVHIRYRGWNAQTMKCFQAFWVHAKSSWNVDYTPTQMGHSNSNGCHTGKWKQQAREEPDTVWDWGQYKMPFKCTVEMFATDHEMCCWGRSPRWRECECGIQFLNAEVEKRMSWPCLWTGPTQPIGVFDQIDDGWCDSVLSIHHRQSEYWATTITISRWTDFRDQNNACEGQNCGLMLQPDDGVLSDRSCQLFTSGCNKFYTWFQTCECGRKLCWRVMHYMNQMHSNYQTEACHNKCSLRMKNTNSFDNYVQQWHCAAYSCNWRFRHCHLNQEIVADQFIMPAVIQFHERTNNKITWYELRRLFMQGLHHFDHIYHYSEEIGSESTIKHEWSDDVVCFSCNDQCKDKHKGMPIHSDKRCVNHTESYYDMFDKWGKHMWWGHDKRLMCNCFFHFGVSIAQQCLVNMYPTFHRNGVLCCFPHRGQWADMRTKRVASGTPWKHVIDHQKWVHVQFCPLGGGQVYYEQASNNDGTSDMFWFLDDFLWTFTKWIWRFIPNAHQVTNTCRNQNGKMSKDAWTDGIKKYVKGGLPQDIVENNCANMGMKN'

for i in range(len(s)):
    cnt*=dict[s[i]]
    cnt = cnt% 1000000

print(3*cnt%1000000)
