s= 'FPDLQDMNCAIDQSTDICPLTQWKMTSLGIPHFEVNRNHARGEKSKFPMYFCRIRSGPKQNIMMHLKKVNEFPVNGGEDVEWSTCQSMYVAGLVSEMTEHNNPCMCNYIPMFGVAIEKDCNVVHPNTRYHDTRWSWLKGWDNIWECPIEWFNGHLLHEYEWFMPNQHPRWHQRARNRHMIHHKQSSPKINPWTKAEPAFMYYRLFAYLALHVYDFRPTKIPVHDPRQSMTGVVHYACIILFMCADYAWHRGWAMISMWTAKISSDASDPDFKGYKYTINWRDYVENVHIYLDTTFTWDYVSLFVKMGTEDTMSQVSNNKVVCSHEHQVGTAQYGYFICAIDEKTTPECWSRNRFILEDWKYNMMCKMEPPKMGADPAQPLCCAWLTIHEVGRTYHVWELVVERFFKRVNTFWRFFSFKCNGPHVNQFVQFELIEYGYQCHALFGQPWRNLRKPDCSLQCNMRYEWDTLGCTSDCVYWVAFPFNKICVIFDGVVTGTQSINSNACKKDHRGMNEHQQFYALCGAAWEHVFCTEKVYDQINLIHRDSCIKLRKLDTDTNGAYNCRDKKGRNNRFILEPVGTQDPQMKKWERPMWKKAGSWAQIVCYEATRAKTWDHGAITDDGGCKDPGCSKQFPKDASTNARQNHTIWHLAHCKYRAPINEACPCSMDEREQSGQYFLDCACITRPMRDDVMTKSVSDMVQKRLGHSAVPCAGAFTMRKMGNGKHSMEPLPSDSLPAKSHEGMTVYQNLYESIARPKGQGVGWYTCPPEMIREAYNRATTSVRPVCPLSIRLWFPIKSDHKSCIFCAQSHISLCMGCGLECRYQASKNKVAMNRQEIWQDRLCHWYK'

f = open("massTable.txt")

raw = f.readlines()

list = []


for i in range(len(raw)):
    list.append(raw[i].split())

dict={}

for i in range(len(raw)):
    dict[list[i][0]]=list[i][1]

print(dict)

cnt=0

for i in range(len(s)):
    cnt+=float(dict[s[i]])

print(round(cnt,4))